name: 'Unit Tests'

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened, labeled]
  push:
    branches:
      - master

jobs:
  unit-tests:
    name: 'Unit Tests'
    runs-on: ubuntu-latest
    if: ${{github.event.pull_requests.labels.*.name == 'feature'}} || ${{github.event.pull_requests.labels.*.name == 'bug'}} || ${{github.event.pull_requests.labels.*.name == 'patch'}}
    env:
      working-directory: ./tests/mcp
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{env.working-directory}}

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
      
    # Install Python
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Install the latest version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false

    # Run unit tests in MCP module
    - name: Run MCP unit tests
      run: |
        cd unit_tests
        MESSAGE="PASSED: All unit tests passed"
        for dir in $(find $(pwd) \( -type f -name 'main.tf' \) |  sed -r 's|/[^/]+$||'); do
          echo "Directory: ${dir}"
          cd $dir
          terraform init
          terraform apply -auto-approve
          for key in $(terraform output -json | jq -r 'keys[]'); do
            output=$(terraform output -json $key)
            result=$(echo $output | jq -r '.result')
            echo ${result^^}
            if [ "$result" != "pass" ]
            then
              MESSAGE="FAIL: There are failed unit tests"
              echo "    Expected data: $(echo $output | jq -r '.expected')"
              echo "    Received data: $(echo $output | jq -r '.received')"
              EXIT_CODE=3
            fi
          done
        done
        echo $MESSAGE
        exit $EXIT_CODE

    # TODO: Add steps for other infrastructure module unit tests
